<a href="https://colab.research.google.com/github/tipir007/html-my-resume/blob/main/coda_P0LC_Christopher_Roberto.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

/*
P0LC1
Nama: Christopher Roberto
Batch: RMT-010
*/

In [10]:
# Connecting Google Colab with Google BigQuery

from google.colab import auth
from google.cloud import bigquery
auth.authenticate_user()
print('Authenticated')

Authenticated

In [11]:
project_id_akun = 'hacktive-christopher' # Gunakan GoolgeCloudPlatform Project-ID Anda
client = bigquery.Client(project=project_id_akun)

In [13]:
# Show the dataset

df = client.query('''

select *
from bigquery-public-data.san_francisco_bikeshare.bikeshare_trips
limit 10

''').to_dataframe()

df

,trip_id,duration_sec,start_date,start_station_name,start_station_id,end_date,end_station_name,end_station_id,bike_number,zip_code,...,c_subscription_type,start_station_latitude,start_station_longitude,end_station_latitude,end_station_longitude,member_birth_year,member_gender,bike_share_for_all_trip,start_station_geom,end_station_geom
0,201709161438302635,1664,2017-09-16 14:38:30+00:00,10th Ave at E 15th St,222,2017-09-16 15:06:15+00:00,10th Ave at E 15th St,222,2635,None,...,None,37.792714,-122.248780,37.792714,-122.24878,1980,Male,None,POINT(-122.2487796 37.7927143),POINT(-122.2487796 37.7927143)
1,201710082321501464,763,2017-10-08 23:21:50+00:00,10th St at Fallon St,201,2017-10-08 23:34:33+00:00,10th Ave at E 15th St,222,1464,None,...,None,37.797673,-122.262997,37.792714,-122.24878,<NA>,None,None,POINT(-122.2629973 37.7976728),POINT(-122.2487796 37.7927143)
2,201708152357422491,965,2017-08-15 23:57:42+00:00,10th St at Fallon St,201,2017-08-16 00:13:48+00:00,10th Ave at E 15th St,222,2491,None,...,None,37.797673,-122.262997,37.792714,-122.24878,<NA>,None,None,POINT(-122.2629973 37.7976728),POINT(-122.2487796 37.7927143)
3,20170815235745207,964,2017-08-15 23:57:45+00:00,10th St at Fallon St,201,2017-08-16 00:13:49+00:00,10th Ave at E 15th St,222,207,None,...,None,37.797673,-122.262997,37.792714,-122.24878,<NA>,None,None,POINT(-122.2629973 37.7976728),POINT(-122.2487796 37.7927143)
4,20170809213205818,781,2017-08-09 21:32:05+00:00,10th St at Fallon St,201,2017-08-09 21:45:06+00:00,10th Ave at E 15th St,222,818,None,...,None,37.797673,-122.262997,37.792714,-122.24878,<NA>,None,None,POINT(-122.2629973 37.7976728),POINT(-122.2487796 37.7927143)
5,20171215164722144,501,2017-12-15 16:47:22+00:00,10th St at Fallon St,201,2017-12-15 16:55:44+00:00,10th Ave at E 15th St,222,144,None,...,None,37.797673,-122.262997,37.792714,-122.24878,1984,Male,None,POINT(-122.2629973 37.7976728),POINT(-122.2487796 37.7927143)
6,20170908003456886,462,2017-09-08 00:34:56+00:00,10th St at Fallon St,201,2017-09-08 00:42:38+00:00,10th Ave at E 15th St,222,886,None,...,None,37.797673,-122.262997,37.792714,-122.24878,1969,Male,None,POINT(-122.2629973 37.7976728),POINT(-122.2487796 37.7927143)
7,201803101333242782,614,2018-03-10 13:33:24+00:00,10th St at Fallon St,201,2018-03-10 13:43:39+00:00,10th Ave at E 15th St,222,2782,None,...,None,37.797673,-122.262997,37.792714,-122.24878,1984,Male,Yes,POINT(-122.2629973 37.7976728),POINT(-122.2487796 37.7927143)
8,201712011430173183,591,2017-12-01 14:30:17+00:00,10th St at Fallon St,201,2017-12-01 14:40:08+00:00,10th Ave at E 15th St,222,3183,None,...,None,37.797673,-122.262997,37.792714,-122.24878,1981,Male,None,POINT(-122.2629973 37.7976728),POINT(-122.2487796 37.7927143)
9,20171111144704480,288,2017-11-11 14:47:04+00:00,12th St at 4th Ave,233,2017-11-11 14:51:53+00:00,10th Ave at E 15th St,222,480,None,...,None,37.795812,-122.255555,37.792714,-122.24878,1969,Male,None,POINT(-122.2555549 37.7958125),POINT(-122.2487796 37.7927143)

In [21]:
# No. 1 Jumlah total perjalanan dari setiap stasiun selama tahun 2023. urut dari yg terbanyak

df1 = client.query('''

SELECT start_station_name,
COUNT (start_station_id) as total_perjalanan
FROM bigquery-public-data.san_francisco_bikeshare.bikeshare_trips
WHERE EXTRACT(YEAR FROM start_date) = 2023
GROUP BY start_station_name
ORDER BY total_perjalanan DESC


''').to_dataframe()

df1

Empty DataFrame
Columns: [start_station_name, total_perjalanan]
Index: []

In [32]:
# No 2 Rata-rata durasi perjalanan (dalam menit) yang dilakukan oleh pelanggan yang menggunakan e-bikes (num_ebikes_available > 0), Juni 2023
df2 = client.query( '''
select AVG(duration_sec)/60 as rata_rata_durasi,
COUNT (bike_number) as total_ebike

from bigquery-public-data.san_francisco_bikeshare.bikeshare_trips
where EXTRACT(MONTH FROM start_date) = 6 AND EXTRACT (YEAR FROM start_date) = 2023
''' ). to_dataframe()

df2

   rata_rata_durasi  total_ebike
0               NaN            0

In [37]:
# No 3 Stasiun dengan ketersediaan sepeda paling sedikit pada akhir bulan Desember 2023 (show table )
df0 = client.query( '''
SELECT * FROM bigquery-public-data.san_francisco_bikeshare.bikeshare_station_status
LIMIT 50

 ''' ).to_dataframe()
df0

,station_id,num_bikes_available,num_bikes_disabled,num_docks_available,num_docks_disabled,is_installed,is_renting,is_returning,last_reported,num_ebikes_available,eightd_has_available_keys
0,676591be-48bc-4653-995a-c4536e793135,0,11,8,0,True,False,False,1755970231,0,False
1,13d36dad-f238-426c-9525-ec73552fa0b0,0,0,22,1,True,True,True,1755994975,0,False
2,ccf416f8-ccc0-4f82-a659-e5d7851d2bcb,0,0,23,0,True,True,True,1755994948,0,False
3,71944da6-f667-4ca6-ace6-70765d46a529,0,0,26,1,True,True,True,1755994927,0,False
4,9cac67a2-9219-455e-b3db-c771311c5b33,0,0,14,0,True,True,True,1755994944,0,False
5,987bd538-e619-4284-beb8-c13c65fcf38b,0,1,31,0,True,True,True,1755994893,0,False
6,b65fc6af-b92c-41c5-8c63-e26cdfa3cda1,0,0,17,0,True,True,True,1755994973,0,False
7,2115876786602304360,0,0,23,0,True,True,True,1755994970,0,False
8,1867619298909571302,0,0,23,0,True,True,True,1755994876,0,False
9,36d93f40-149d-4b0d-ab4c-ea4aad093937,0,2,16,0,True,True,True,1755994945,0,False
10,22a9d86b-ba44-4f2f-b167-355f99c7968c,0,1,26,0,True,True,True,1755994969,0,False
11,3144f47a-86f7-40f6-9ff0-5c8120babf6a,0,1,25,1,True,True,True,1755994955,0,False
12,8013d0b6-dd3a-4f9f-9fee-a1e6e21aef90,0,1,25,1,True,True,True,1755994982,0,False
13,87168190-5491-47c8-bb9b-187ddf6052c3,0,0,43,0,True,True,True,1755994923,0,False
14,dcb5ad16-caa9-4d40-b279-6d36152069a2,0,1,35,0,True,True,True,1755994980,0,False
15,314fd7e5-4335-4b89-ac9d-2c099bc33d9f,0,0,19,0,True,True,True,1755994937,0,False
16,b6190b6b-1f42-4b69-ab79-d6cfa18adea7,0,0,18,0,True,True,True,1755994870,0,False
17,2ed84bed-e42a-4f0d-a059-78a709748616,0,0,19,0,True,True,True,1755994893,0,False
18,3a415706-d63c-4a35-9b1c-bb9127ddc925,0,0,22,0,True,True,True,1755994895,0,False
19,586dce76-7324-4117-9c58-7ed6d00151bf,0,2,24,0,True,True,True,1755994911,0,False
20,ba25987f-399d-49ce-9354-52785e48ea13,0,2,37,0,True,True,True,1755994980,0,False
21,1880193329986742734,0,0,5,0,True,True,True,1700076043,0,False
22,1880193329986742718,0,0,4,0,True,True,True,1700075155,0,False
23,1875048568201626296,0,0,5,0,True,True,True,1698950614,0,False
24,1841972814951361206,0,0,10,0,True,True,True,1691416974,0,False
25,1880193325691775420,0,0,4,0,True,True,True,1700070622,0,False
26,1881006687679115446,0,0,20,0,True,True,True,1754321880,0,False
27,1880942617512231608,0,0,16,0,True,True,True,1700245080,0,False
28,1880193329986742724,0,0,3,0,True,True,True,1700070623,0,False
29,1841972814951361204,0,0,5,0,True,True,True,1691418718,0,False
30,6732f1f5-616c-46bc-81e6-67c5319b3c73,1,0,29,0,True,True,True,1755994946,0,False
31,1854261997570128336,1,0,18,0,True,True,True,1755994949,0,False
32,1924343126095301624,1,0,24,0,True,True,True,1755994920,0,False
33,a7a6f245-fb70-495f-9598-89fa03d120f7,1,1,25,0,True,True,True,1755994970,0,False
34,2051719798880811946,1,1,21,0,True,True,True,1755994977,0,False
35,175541bb-0ac6-42ba-bb50-071317d1237b,1,1,21,0,True,True,True,1755994923,0,False
36,bf7e294f-11cc-4b4a-9a37-036d0dc0f648,1,0,15,0,True,True,True,1755994894,0,False
37,df4b01d6-90bb-4faa-8437-d0391b8d115b,1,1,22,0,True,True,True,1755994983,0,False
38,3612155a-0fb2-4e66-8bab-f81979bfe54a,2,1,23,1,True,True,True,1755994932,0,False
39,d79ae08e-a8d2-4aad-9f98-9b20afb8f6e0,2,1,15,0,True,True,True,1755994982,0,False
40,a6c2bd25-bdaf-4548-baeb-e203cfa52b3e,2,0,17,0,True,True,True,1755994980,0,False
41,1853888259818405998,2,0,13,0,True,True,True,1755994954,0,False
42,2088720616476988050,2,0,16,0,True,True,True,1755994956,0,False
43,9fae2998-e458-47f8-9c7c-978e01f05330,2,0,17,0,True,True,True,1755994916,0,False
44,75f6691a-df0a-4d7a-8b35-e5ffe33add4f,2,1,15,0,True,True,True,1755994968,0,False
45,4938bd2c-37c1-4be9-9ad3-3b3d3d589248,3,0,15,0,True,True,True,1755994880,0,False
46,1926579821872118770,3,4,14,0,True,True,True,1755994923,0,False
47,d88b1cad-d8e4-4eff-9897-9dabbc43bcbb,3,1,27,0,True,True,True,1755994973,0,False
48,90e4028e-afee-480f-b327-4e7cc40f6796,3,1,23,0,True,True,True,1755994929,0,False
49,2114365359206953814,4,0,12,0,True,True,True,1755994889,0,False

In [43]:
# No 3 Stasiun dengan ketersediaan sepeda paling sedikit pada akhir bulan Desember 2023
df3 = client.query('''
SELECT station_id, num_bikes_available
FROM bigquery-public-data.san_francisco_bikeshare.bikeshare_station_status
WHERE EXTRACT(MONTH FROM TIMESTAMP_MILLIS(last_reported * 1000)) = 12
  AND EXTRACT(YEAR FROM TIMESTAMP_MILLIS(last_reported * 1000)) = 2023
ORDER BY num_bikes_available ASC
LIMIT 1

''').to_dataframe()
df3

Empty DataFrame
Columns: [station_id, num_bikes_available]
Index: []

In [48]:
# No 4 Jumlah total perjalanan oleh pengguna wanita pada Sem 1 2024
df4 = client.query('''
SELECT COUNT(trip_id) as total_perjalanan
FROM bigquery-public-data.san_francisco_bikeshare.bikeshare_trips
WHERE EXTRACT(YEAR FROM start_date) = 2024
AND EXTRACT(MONTH FROM start_date) <= 6
AND member_gender = 'female'

''').to_dataframe()
df4

   total_perjalanan
0                 0

In [49]:
# No 5 URUTAN daerah dengan jumlah stasiun terbanyak hingga paling sedikit
df00 = client.query( '''
SELECT bikeshare_station_info.region_id, bikeshare_station_info.station_id, bikeshare_station_info.name
FROM bigquery-public-data.san_francisco_bikeshare.bikeshare_station_info
LIMIT 50

 ''' ).to_dataframe()
df00

    region_id station_id                                               name
0        <NA>        523        Lafayette Park (Laguna St at Washington St)
1        <NA>        501  Balboa Park (San Jose Ave at Sgt. John V. Youn...
2        <NA>        504                       Onondaga Ave at Alemany Blvd
3        <NA>        539                    North Point St at Divisadero St
4        <NA>        535                          Filbert St at Fillmore St
5        <NA>        505                            Geneva Ave at Moscow St
6        <NA>        544                 Allyne Park (Green St at Gough St)
7        <NA>        546                              13th St at Webster St
8        <NA>        536                        Fillmore St at Jefferson St
9           3        412                             Glen Park BART Station
10          3        386                             24th St at Bartlett St
11          3        499                                Otis St at Brady St
12          3        400                      Buchanan St at North Point St
13          3         37                                2nd St at Folsom St
14          3         38                         The Embarcadero at Pier 38
15          3         15  San Francisco Ferry Building (Harry Bridges Pl...
16          3        533                          Front St at California St
17          3         64                               5th St at Brannan St
18          3        479                      Washington St at Van Ness Ave
19          3        108                               16th St Mission BART
20          3        460                Terry Francois Blvd at Warriors Way
21          3        538                               Haight St at Lyon St
22          3        433                      Gennessee St at Monterey Blvd
23          3         62                        Victoria Manalo Draves Park
24          3        446                              Mint St at Mission St
25          3        323                              Broadway at Kearny St
26          3        142                                      Guerrero Park
27          3        145                               29th St at Church St
28          3        140                      Cesar Chavez St at Dolores St
29          3        459                                 Utah St at 24th St
30          3        518                             22nd St at Potrero Ave
31          3        125                               20th St at Bryant St
32          3        119                                  18th St at Noe St
33          3        146                            30th St at San Jose Ave
34          3        144                                       Precita Park
35          3        390                      Indiana St at Cesar Chavez St
36          3        359                          Williams Ave at Apollo St
37          3        437                            Evans Ave at Mendell St
38          3         79                               7th St at Brannan St
39          3        532                              38th Ave at Balboa St
40          3        525                             21st Ave at Geary Blvd
41          3        465  San Francisco Caltrain Station (King St at 4th...
42          3         25                                Howard St at 2nd St
43          3         63                                Bryant St at 6th St
44          3         77                               11th St at Natoma St
45          3        453                               Brannan St at 4th St
46          3        493                                Folsom St at 7th St
47          3        456                        Arguello Blvd at Geary Blvd
48          3        114                         Rhode Island St at 17th St
49          3        376                             Illinois St at 20th St

In [51]:
# No 5 URUTAN daerah dengan jumlah stasiun terbanyak hingga paling sedikit
df5 = client.query( '''
SELECT bikeshare_station_info.region_id, COUNT(bikeshare_station_info.station_id) as total_stasiun
FROM bigquery-public-data.san_francisco_bikeshare.bikeshare_station_info
GROUP BY bikeshare_station_info.region_id
ORDER BY total_stasiun DESC

 ''' ).to_dataframe()
df5

   region_id  total_stasiun
0          3            253
1          5             82
2         12             80
3         14             37
4         13             11
5       <NA>              9

In [59]:
# NO 6 Pada jam berapa perjalanan terbanyak dilakukan dalam satu hari selama bulan mei 2025

df6 = client.query('''
SELECT EXTRACT(HOUR FROM start_date) as jam, COUNT(trip_id) as total_perjalanan
from bigquery-public-data.san_francisco_bikeshare.bikeshare_trips
WHERE EXTRACT(MONTH FROM start_date) =  5 AND EXTRACT(YEAR FROM start_date) = 2025
GROUP BY jam
ORDER BY total_perjalanan DESC
LIMIT 1
''').to_dataframe()
df6

Empty DataFrame
Columns: [jam, total_perjalanan]
Index: []